import turtle
selena=turtle.Turtle()
selena.shape('arrow')
selena.color("red")

win=turtle.Screen()
win.bgcolor("black")
selena.forward(100)
selena.left(45)
selena.fd(100)
selena.left(90)
selena.fd(100)
selena.left(45)
selena.fd(100)
selena.left(45)
selena.fd(100)
selena.left(90)
selena.fd(100)
